package vista;

import controlador.Controlador;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.lang.reflect.Array;
import java.util.Arrays;

import static java.util.Arrays.sort;
import static javax.swing.JOptionPane.showMessageDialog;

/**
 * Created by poo2 on 26/05/2016.
 */
public class DemanaAutobusCombo extends JFrame implements ActionListener {
  private JButton desarButton;
  private JButton sortirButton;
  private JTextField matriculaAutobus;
  private JTextField numeroDePlaces;
  private JComboBox cBLiniaDeBus;
  private JLabel lbMatriculaAutobus;
  private JLabel lbNumDePlaces;
  private JLabel lbLinea;

  private JPanel demanaAutobusosCombo;

  private Controlador ctrl;

  public DemanaAutobusCombo(String nomMenu, Controlador c) {
    super(nomMenu);


    ctrl = c;
    Object[] keys = (Object[]) ctrl.numLinines.keySet().toArray();
    Arrays.sort(keys);

    setContentPane(demanaAutobusosCombo);
    setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    pack();
    setLocationRelativeTo(null);

    desarButton.addActionListener(this);
    sortirButton.addActionListener(this);

//    DefaultComboBoxModel dcbm = new DefaultComboBoxModel(ctrl.numLinines.keySet().toArray());
    DefaultComboBoxModel dcbm = new DefaultComboBoxModel(keys);
    dcbm.insertElementAt(" ", 0);
    dcbm.setSelectedItem(" ");
    cBLiniaDeBus.setModel(dcbm);

    setVisible(true);

  }


  public void actionPerformed(ActionEvent e) {

    String botoApretat;
    System.out.println("Adeu" + e);
    try {
      botoApretat = e.getActionCommand().trim();
    } catch (Exception error) {
      botoApretat = "sortirButton";
      showMessageDialog(this, "Error al introducir datos");
    }

    if (botoApretat.equals("sortirButton")) {
      System.out.println("Sortim!!!");
      setVisible(false); //you can't see me!
      dispose(); //Destroy the JFrame object

    } else if (botoApretat.equals("desarButton")) {
      System.out.println("DESEM: " + matriculaAutobus.getText() + ", " + numeroDePlaces.getText() + ", " + cBLiniaDeBus.getSelectedItem());
      try {
        ctrl.addautobus(matriculaAutobus.getText().trim(),
            Integer.parseInt("0" + numeroDePlaces.getText().trim()),
            Integer.parseInt("" + cBLiniaDeBus.getSelectedItem()));
        showMessageDialog(null, "Guardado correctamente");
        matriculaAutobus.setText("");
        numeroDePlaces.setText("");
        cBLiniaDeBus.setSelectedItem(" ");
      } catch (Exception error) {
        System.err.println("Paràmetres incorrectes");
      }

    }


  }


  {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
    $$$setupUI$$$();
  }

  /**
   * Method generated by IntelliJ IDEA GUI Designer
   * >>> IMPORTANT!! <<<
   * DO NOT edit this method OR call it in your code!
   *
   * @noinspection ALL
   */
  private void $$$setupUI$$$() {
    demanaAutobusosCombo = new JPanel();
    demanaAutobusosCombo.setLayout(new GridBagLayout());
    lbMatriculaAutobus = new JLabel();
    lbMatriculaAutobus.setText("Matricula Autobus");
    GridBagConstraints gbc;
    gbc = new GridBagConstraints();
    gbc.gridx = 0;
    gbc.gridy = 0;
    gbc.anchor = GridBagConstraints.WEST;
    demanaAutobusosCombo.add(lbMatriculaAutobus, gbc);
    final JPanel spacer1 = new JPanel();
    gbc = new GridBagConstraints();
    gbc.gridx = 1;
    gbc.gridy = 0;
    gbc.fill = GridBagConstraints.HORIZONTAL;
    demanaAutobusosCombo.add(spacer1, gbc);
    final JPanel spacer2 = new JPanel();
    gbc = new GridBagConstraints();
    gbc.gridx = 0;
    gbc.gridy = 1;
    gbc.fill = GridBagConstraints.VERTICAL;
    demanaAutobusosCombo.add(spacer2, gbc);
    lbNumDePlaces = new JLabel();
    lbNumDePlaces.setText("Numero de places");
    gbc = new GridBagConstraints();
    gbc.gridx = 0;
    gbc.gridy = 2;
    gbc.anchor = GridBagConstraints.WEST;
    demanaAutobusosCombo.add(lbNumDePlaces, gbc);
    lbLinea = new JLabel();
    lbLinea.setText("Linia Del Bus");
    gbc = new GridBagConstraints();
    gbc.gridx = 0;
    gbc.gridy = 4;
    gbc.anchor = GridBagConstraints.WEST;
    demanaAutobusosCombo.add(lbLinea, gbc);
    final JPanel spacer3 = new JPanel();
    gbc = new GridBagConstraints();
    gbc.gridx = 0;
    gbc.gridy = 3;
    gbc.fill = GridBagConstraints.VERTICAL;
    demanaAutobusosCombo.add(spacer3, gbc);
    final JPanel spacer4 = new JPanel();
    gbc = new GridBagConstraints();
    gbc.gridx = 0;
    gbc.gridy = 5;
    gbc.fill = GridBagConstraints.VERTICAL;
    demanaAutobusosCombo.add(spacer4, gbc);
    final JPanel spacer5 = new JPanel();
    gbc = new GridBagConstraints();
    gbc.gridx = 0;
    gbc.gridy = 6;
    gbc.fill = GridBagConstraints.HORIZONTAL;
    gbc.ipadx = 120;
    demanaAutobusosCombo.add(spacer5, gbc);
    final JPanel spacer6 = new JPanel();
    gbc = new GridBagConstraints();
    gbc.gridx = 2;
    gbc.gridy = 6;
    gbc.fill = GridBagConstraints.HORIZONTAL;
    gbc.ipadx = 100;
    demanaAutobusosCombo.add(spacer6, gbc);
    final JPanel spacer7 = new JPanel();
    gbc = new GridBagConstraints();
    gbc.gridx = 3;
    gbc.gridy = 6;
    gbc.fill = GridBagConstraints.HORIZONTAL;
    gbc.ipadx = 50;
    demanaAutobusosCombo.add(spacer7, gbc);
    final JPanel spacer8 = new JPanel();
    gbc = new GridBagConstraints();
    gbc.gridx = 4;
    gbc.gridy = 6;
    gbc.fill = GridBagConstraints.HORIZONTAL;
    gbc.ipadx = 50;
    demanaAutobusosCombo.add(spacer8, gbc);
    desarButton = new JButton();
    desarButton.setActionCommand("desarButton");
    desarButton.setText("Desar");
    gbc = new GridBagConstraints();
    gbc.gridx = 3;
    gbc.gridy = 7;
    gbc.fill = GridBagConstraints.HORIZONTAL;
    demanaAutobusosCombo.add(desarButton, gbc);
    sortirButton = new JButton();
    sortirButton.setActionCommand("sortirButton");
    sortirButton.setText("Sortir");
    gbc = new GridBagConstraints();
    gbc.gridx = 4;
    gbc.gridy = 7;
    gbc.fill = GridBagConstraints.HORIZONTAL;
    demanaAutobusosCombo.add(sortirButton, gbc);
    numeroDePlaces = new JTextField();
    numeroDePlaces.setText("");
    gbc = new GridBagConstraints();
    gbc.gridx = 2;
    gbc.gridy = 2;
    gbc.anchor = GridBagConstraints.WEST;
    gbc.fill = GridBagConstraints.HORIZONTAL;
    demanaAutobusosCombo.add(numeroDePlaces, gbc);
    matriculaAutobus = new JTextField();
    matriculaAutobus.setText("");
    gbc = new GridBagConstraints();
    gbc.gridx = 2;
    gbc.gridy = 0;
    gbc.anchor = GridBagConstraints.WEST;
    gbc.fill = GridBagConstraints.HORIZONTAL;
    demanaAutobusosCombo.add(matriculaAutobus, gbc);
    final JPanel spacer9 = new JPanel();
    gbc = new GridBagConstraints();
    gbc.gridx = 1;
    gbc.gridy = 6;
    gbc.fill = GridBagConstraints.VERTICAL;
    demanaAutobusosCombo.add(spacer9, gbc);
    cBLiniaDeBus = new JComboBox();
    gbc = new GridBagConstraints();
    gbc.gridx = 2;
    gbc.gridy = 4;
    gbc.anchor = GridBagConstraints.WEST;
    gbc.fill = GridBagConstraints.HORIZONTAL;
    demanaAutobusosCombo.add(cBLiniaDeBus, gbc);
  }

  /**
   * @noinspection ALL
   */
  public JComponent $$$getRootComponent$$$() {
    return demanaAutobusosCombo;
  }
}
