package vista;

import controlador.Controlador;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Arrays;

import static javax.swing.JOptionPane.showMessageDialog;

/**
 * Created by joan on 28/05/2016.
 */
public class DemanaCAprenent extends JFrame implements ActionListener {
  private JList llistaLiniesAssignades;

  private JPanel demanaCBAprenent;

  private Controlador ctrl;

  public DemanaCAprenent(String nomMenu, Controlador c) {
    super(nomMenu);

    ctrl = c;
    Object[] keys = (Object[]) ctrl.numLinines.keySet().toArray();
    Arrays.sort(keys);

    setContentPane(demanaCBAprenent);
    setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    pack();
    setLocationRelativeTo(null);

//    desarButton.addActionListener(this);
//    sortirButton.addActionListener(this);

//    DefaultComboBoxModel dcbm = new DefaultComboBoxModel(ctrl.numLinines.keySet().toArray());
/*
    DefaultComboBoxModel dcbm = new DefaultComboBoxModel(keys);
    dcbm.insertElementAt(" ", 0);
    dcbm.setSelectedItem(" ");
    cBLiniaDeBus.setModel(dcbm);
*/
    setVisible(true);


  }

  public static void main(String[] args) {
    Controlador controlador = new Controlador();
    new DemanaCAprenent("Demana Aprenent", controlador);

  }

  public void actionPerformed(ActionEvent e) {
/*
    String botoApretat;
    System.out.println("Adeu" + e);
    try {
      botoApretat = e.getActionCommand().trim();
    } catch (Exception error) {
      botoApretat = "sortirButton";
      showMessageDialog(this, "Error al introducir datos");
    }

    if (botoApretat.equals("sortirButton")) {
      System.out.println("Sortim!!!");
      setVisible(false); //you can't see me!
      dispose(); //Destroy the JFrame object

    } else if (botoApretat.equals("desarButton")) {
      System.out.println("DESEM: " + dni.getText() + ", " + nomConductor.getText() + ", " + Integer.parseInt("0" + cBLiniaDeBus.getSelectedItem()));
      try {
        ctrl.addCondVetera(dni.getText().trim(),
            nomConductor.getText().trim(),
            Integer.parseInt("0" + cBLiniaDeBus.getSelectedItem()));
        showMessageDialog(null, "Guardado correctamente");
        dni.setText("");
        nomConductor.setText("");
        cBLiniaDeBus.setSelectedItem(" ");
      } catch (Exception error) {
        System.err.println("Paràmetres incorrectes");
      }

    }

*/
  }



  {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
    $$$setupUI$$$();
  }

  /**
   * Method generated by IntelliJ IDEA GUI Designer
   * >>> IMPORTANT!! <<<
   * DO NOT edit this method OR call it in your code!
   *
   * @noinspection ALL
   */
  private void $$$setupUI$$$() {
    demanaCBAprenent = new JPanel();
    demanaCBAprenent.setLayout(new GridBagLayout());
    llistaLiniesAssignades = new JList();
    GridBagConstraints gbc;
    gbc = new GridBagConstraints();
    gbc.gridx = 0;
    gbc.gridy = 0;
    gbc.fill = GridBagConstraints.BOTH;
    gbc.ipadx = 100;
    gbc.ipady = 100;
    demanaCBAprenent.add(llistaLiniesAssignades, gbc);
    final JPanel spacer1 = new JPanel();
    gbc = new GridBagConstraints();
    gbc.gridx = 0;
    gbc.gridy = 1;
    gbc.fill = GridBagConstraints.VERTICAL;
    gbc.ipadx = 100;
    demanaCBAprenent.add(spacer1, gbc);
    final JPanel spacer2 = new JPanel();
    gbc = new GridBagConstraints();
    gbc.gridx = 1;
    gbc.gridy = 0;
    gbc.fill = GridBagConstraints.VERTICAL;
    gbc.ipady = 100;
    demanaCBAprenent.add(spacer2, gbc);
  }

  /**
   * @noinspection ALL
   */
  public JComponent $$$getRootComponent$$$() {
    return demanaCBAprenent;
  }
}

