package vista;

import controlador.Controlador;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import static javax.swing.JOptionPane.showMessageDialog;

/**
 * Created by poo2 on 25/05/2016.
 */
public class DemanaLinea extends JFrame implements ActionListener {
  private JPanel demanaLinea;
  private JTextField numLinia;
  private JButton desarButton;
  private JButton sortirButton;

  private Controlador ctrl;

  public DemanaLinea(String nomMenu, Controlador c) {
    super(nomMenu);

    ctrl = c;
    setContentPane(demanaLinea);
    setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    pack();
    setLocationRelativeTo(null);


    setVisible(true);


    desarButton.addActionListener(new ActionListener() {
      @Override
      public void actionPerformed(ActionEvent e) {
        //desar
        try {
          ctrl.addLinia(Integer.parseInt(numLinia.getText().trim()));
          showMessageDialog(null, "Guardado correctamente" + numLinia.getText());
          numLinia.setText("");
        } catch (Exception error) {
          System.err.println("Paràmetres incorrectes");
        }
      }
    });


    sortirButton.addActionListener(new ActionListener() {
      @Override
      public void actionPerformed(ActionEvent e) {
        // tancar
        System.out.println("sortim Demanar Linea!!!");
        setVisible(false); //you can't see me!
        dispose(); //Destroy the JFrame object

      }
    });
  }


  public static void main(String[] args) {
    DemanaLinea dLinea = new DemanaLinea("Demanar Línia", null);

  }

  @Override
  public void actionPerformed(ActionEvent e) {

  }

  {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
    $$$setupUI$$$();
  }

  /**
   * Method generated by IntelliJ IDEA GUI Designer
   * >>> IMPORTANT!! <<<
   * DO NOT edit this method OR call it in your code!
   *
   * @noinspection ALL
   */
  private void $$$setupUI$$$() {
    demanaLinea = new JPanel();
    demanaLinea.setLayout(new GridBagLayout());
    final JLabel label1 = new JLabel();
    label1.setText("Numero de Linia: ");
    GridBagConstraints gbc;
    gbc = new GridBagConstraints();
    gbc.gridx = 0;
    gbc.gridy = 0;
    gbc.anchor = GridBagConstraints.EAST;
    demanaLinea.add(label1, gbc);
    final JPanel spacer1 = new JPanel();
    gbc = new GridBagConstraints();
    gbc.gridx = 1;
    gbc.gridy = 0;
    gbc.fill = GridBagConstraints.HORIZONTAL;
    demanaLinea.add(spacer1, gbc);
    final JPanel spacer2 = new JPanel();
    gbc = new GridBagConstraints();
    gbc.gridx = 0;
    gbc.gridy = 1;
    gbc.fill = GridBagConstraints.VERTICAL;
    demanaLinea.add(spacer2, gbc);
    numLinia = new JTextField();
    numLinia.setText("");
    gbc = new GridBagConstraints();
    gbc.gridx = 2;
    gbc.gridy = 0;
    gbc.anchor = GridBagConstraints.WEST;
    gbc.fill = GridBagConstraints.HORIZONTAL;
    demanaLinea.add(numLinia, gbc);
    desarButton = new JButton();
    desarButton.setText("Desar");
    gbc = new GridBagConstraints();
    gbc.gridx = 2;
    gbc.gridy = 2;
    gbc.fill = GridBagConstraints.HORIZONTAL;
    demanaLinea.add(desarButton, gbc);
    sortirButton = new JButton();
    sortirButton.setText("Sortir");
    gbc = new GridBagConstraints();
    gbc.gridx = 3;
    gbc.gridy = 2;
    gbc.fill = GridBagConstraints.HORIZONTAL;
    demanaLinea.add(sortirButton, gbc);
    final JPanel spacer3 = new JPanel();
    gbc = new GridBagConstraints();
    gbc.gridx = 2;
    gbc.gridy = 1;
    gbc.fill = GridBagConstraints.HORIZONTAL;
    gbc.ipadx = 10;
    demanaLinea.add(spacer3, gbc);
    final JPanel spacer4 = new JPanel();
    gbc = new GridBagConstraints();
    gbc.gridx = 3;
    gbc.gridy = 1;
    gbc.fill = GridBagConstraints.HORIZONTAL;
    gbc.ipadx = 10;
    demanaLinea.add(spacer4, gbc);
    final JPanel spacer5 = new JPanel();
    gbc = new GridBagConstraints();
    gbc.gridx = 0;
    gbc.gridy = 3;
    gbc.fill = GridBagConstraints.HORIZONTAL;
    gbc.ipadx = 100;
    demanaLinea.add(spacer5, gbc);
  }

  /**
   * @noinspection ALL
   */
  public JComponent $$$getRootComponent$$$() {
    return demanaLinea;
  }
}
