package vista;

import controlador.Controlador;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import static javax.swing.JOptionPane.showMessageDialog;

/**
 * Created by poo2 on 25/05/2016.
 */
public class DemanaAutobusos extends JFrame implements ActionListener {
  private JLabel matriculaAutobus;
  private JButton desarButton;
  private JButton sortirButton;
  private JTextField matriculaBus;
  private JTextField numPlaces;
  private JTextField liniaDeBus;
  private JPanel demanaAutobusos;

  private Controlador ctrl;


  public DemanaAutobusos(String nomMenu, Controlador c) {
    super(nomMenu);

    ctrl = c;
    setContentPane(demanaAutobusos);
    setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    pack();
    setLocationRelativeTo(null);


    setVisible(true);


    desarButton.addActionListener(new ActionListener() {
      @Override
      public void actionPerformed(ActionEvent e) {
        //desar
        try {
          ctrl.addautobus(matriculaBus.getText().trim(),
              Integer.parseInt("0" + numPlaces.getText().trim()),
              Integer.parseInt("0" + liniaDeBus.getText().trim()));

          showMessageDialog(null, "Guardado correctamente" + matriculaBus.getText());
        } catch (Exception error) {
          System.err.println("Paràmetres incorrectes");
        }
      }
    });

    sortirButton.addActionListener(new ActionListener() {
      @Override
      public void actionPerformed(ActionEvent e) {
        // tancar
        System.out.println("sortim Demanar Linea!!!");
        setVisible(false); //you can't see me!
        dispose(); //Destroy the JFrame object

      }
    });
  }

  @Override
  public void actionPerformed(ActionEvent e) {

  }

  {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
    $$$setupUI$$$();
  }

  /**
   * Method generated by IntelliJ IDEA GUI Designer
   * >>> IMPORTANT!! <<<
   * DO NOT edit this method OR call it in your code!
   *
   * @noinspection ALL
   */
  private void $$$setupUI$$$() {
    demanaAutobusos = new JPanel();
    demanaAutobusos.setLayout(new GridBagLayout());
    final JPanel spacer1 = new JPanel();
    GridBagConstraints gbc;
    gbc = new GridBagConstraints();
    gbc.gridx = 2;
    gbc.gridy = 2;
    gbc.fill = GridBagConstraints.HORIZONTAL;
    demanaAutobusos.add(spacer1, gbc);
    final JPanel spacer2 = new JPanel();
    gbc = new GridBagConstraints();
    gbc.gridx = 0;
    gbc.gridy = 3;
    gbc.gridwidth = 2;
    gbc.fill = GridBagConstraints.VERTICAL;
    demanaAutobusos.add(spacer2, gbc);
    final JPanel spacer3 = new JPanel();
    gbc = new GridBagConstraints();
    gbc.gridx = 1;
    gbc.gridy = 5;
    gbc.fill = GridBagConstraints.VERTICAL;
    demanaAutobusos.add(spacer3, gbc);
    final JLabel label1 = new JLabel();
    label1.setText("Linia Del Bus");
    gbc = new GridBagConstraints();
    gbc.gridx = 1;
    gbc.gridy = 6;
    gbc.anchor = GridBagConstraints.WEST;
    demanaAutobusos.add(label1, gbc);
    final JLabel label2 = new JLabel();
    label2.setText("Numero de places");
    gbc = new GridBagConstraints();
    gbc.gridx = 1;
    gbc.gridy = 4;
    gbc.gridwidth = 2;
    gbc.anchor = GridBagConstraints.WEST;
    demanaAutobusos.add(label2, gbc);
    matriculaAutobus = new JLabel();
    matriculaAutobus.setText("Matricula Autobus");
    gbc = new GridBagConstraints();
    gbc.gridx = 1;
    gbc.gridy = 2;
    gbc.anchor = GridBagConstraints.WEST;
    demanaAutobusos.add(matriculaAutobus, gbc);
    matriculaBus = new JTextField();
    matriculaBus.setText("");
    gbc = new GridBagConstraints();
    gbc.gridx = 3;
    gbc.gridy = 2;
    gbc.anchor = GridBagConstraints.WEST;
    gbc.fill = GridBagConstraints.HORIZONTAL;
    demanaAutobusos.add(matriculaBus, gbc);
    numPlaces = new JTextField();
    numPlaces.setText("");
    gbc = new GridBagConstraints();
    gbc.gridx = 3;
    gbc.gridy = 4;
    gbc.anchor = GridBagConstraints.WEST;
    gbc.fill = GridBagConstraints.HORIZONTAL;
    demanaAutobusos.add(numPlaces, gbc);
    liniaDeBus = new JTextField();
    liniaDeBus.setText("");
    gbc = new GridBagConstraints();
    gbc.gridx = 3;
    gbc.gridy = 6;
    gbc.anchor = GridBagConstraints.WEST;
    gbc.fill = GridBagConstraints.HORIZONTAL;
    demanaAutobusos.add(liniaDeBus, gbc);
    final JPanel spacer4 = new JPanel();
    gbc = new GridBagConstraints();
    gbc.gridx = 3;
    gbc.gridy = 7;
    gbc.fill = GridBagConstraints.VERTICAL;
    demanaAutobusos.add(spacer4, gbc);
    final JPanel spacer5 = new JPanel();
    gbc = new GridBagConstraints();
    gbc.gridx = 1;
    gbc.gridy = 1;
    gbc.fill = GridBagConstraints.HORIZONTAL;
    gbc.ipadx = 120;
    demanaAutobusos.add(spacer5, gbc);
    sortirButton = new JButton();
    sortirButton.setText("Sortir");
    gbc = new GridBagConstraints();
    gbc.gridx = 5;
    gbc.gridy = 8;
    gbc.fill = GridBagConstraints.HORIZONTAL;
    demanaAutobusos.add(sortirButton, gbc);
    desarButton = new JButton();
    desarButton.setText("Desar");
    gbc = new GridBagConstraints();
    gbc.gridx = 4;
    gbc.gridy = 8;
    gbc.fill = GridBagConstraints.HORIZONTAL;
    demanaAutobusos.add(desarButton, gbc);
    final JPanel spacer6 = new JPanel();
    gbc = new GridBagConstraints();
    gbc.gridx = 4;
    gbc.gridy = 9;
    gbc.fill = GridBagConstraints.HORIZONTAL;
    gbc.ipadx = 50;
    demanaAutobusos.add(spacer6, gbc);
    final JPanel spacer7 = new JPanel();
    gbc = new GridBagConstraints();
    gbc.gridx = 5;
    gbc.gridy = 9;
    gbc.fill = GridBagConstraints.HORIZONTAL;
    gbc.ipadx = 50;
    demanaAutobusos.add(spacer7, gbc);
    final JPanel spacer8 = new JPanel();
    gbc = new GridBagConstraints();
    gbc.gridx = 3;
    gbc.gridy = 0;
    gbc.fill = GridBagConstraints.HORIZONTAL;
    gbc.ipadx = 100;
    demanaAutobusos.add(spacer8, gbc);
  }

  /**
   * @noinspection ALL
   */
  public JComponent $$$getRootComponent$$$() {
    return demanaAutobusos;
  }
}
