package vista;
import controlador.Controlador;

import javax.swing.*;
import javax.swing.border.TitledBorder;

import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import static javax.swing.JOptionPane.showMessageDialog;

/**
 * Created by joan on 24/05/2016.
 */
public class MenuX_jajaja_ni_puta_de_com_va extends JFrame implements ActionListener {

  private JButton altaConductorsButton;
  private JButton altaLíniesButton;
  private JButton altaAutobusosButton;
  private JButton sortirButton;
  private JTextField texto;

  Controlador c;

  public MenuX_jajaja_ni_puta_de_com_va() {
    super("LA aplicación de autobuses");

    setSize(500, 600);

    // La aplicación acaba al darle a la X
    setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

    setLayout(new GridLayout(8, 1));
    add(altaConductorsButton);
    add(altaLíniesButton);
    add(altaAutobusosButton);
    add(sortirButton);

    setVisible(true);

    c = new Controlador();
    altaConductorsButton.addActionListener(new ActionListener() {
      @Override
      public void actionPerformed(ActionEvent actionEvent) {
        showMessageDialog(null, "Clicat altaConductorsButton");
      }
    });
    altaLíniesButton.addActionListener(new ActionListener() {
      @Override
      public void actionPerformed(ActionEvent actionEvent) {
        showMessageDialog(null, "Clicat altaLíniesButton");
      }
    });
    altaAutobusosButton.addActionListener(new ActionListener() {
      @Override
      public void actionPerformed(ActionEvent actionEvent) {
        showMessageDialog(null, "Clicat altaAutobusosButton");
      }
    });
    sortirButton.addActionListener(new ActionListener() {
      @Override
      public void actionPerformed(ActionEvent actionEvent) {
        showMessageDialog(null, "Clicat sortirButton");

      }
    });
  }

  public static void main(String[] args) {
    MenuX_jajaja_ni_puta_de_com_va marco = new MenuX_jajaja_ni_puta_de_com_va();


  }

  public void actionPerformed(ActionEvent e) {

    System.out.println(e);
    try {
      c.addLinia(Integer.parseInt(texto.getText()));
      showMessageDialog(this, "Guardado correctamente");
    } catch (Exception error) {
      showMessageDialog(this, "Error al introducir datos");
    }
  }

  public void setData(MenuX_jajaja_ni_puta_de_com_va data) {
  }

  public void getData(MenuX_jajaja_ni_puta_de_com_va data) {
  }

  public boolean isModified(MenuX_jajaja_ni_puta_de_com_va data) {
    return false;
  }

  {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
    $$$setupUI$$$();
  }

  /**
   * Method generated by IntelliJ IDEA GUI Designer
   * >>> IMPORTANT!! <<<
   * DO NOT edit this method OR call it in your code!
   *
   * @noinspection ALL
   */
  private void $$$setupUI$$$() {
    final JPanel panel1 = new JPanel();
    panel1.setLayout(new GridBagLayout());
    panel1.setBorder(BorderFactory.createTitledBorder(null, "Menu Principal", TitledBorder.CENTER, TitledBorder.DEFAULT_POSITION));
    altaLíniesButton = new JButton();
    altaLíniesButton.setText("Alta Línies");
    GridBagConstraints gbc;
    gbc = new GridBagConstraints();
    gbc.gridx = 1;
    gbc.gridy = 1;
    gbc.fill = GridBagConstraints.HORIZONTAL;
    panel1.add(altaLíniesButton, gbc);
    altaAutobusosButton = new JButton();
    altaAutobusosButton.setHorizontalTextPosition(11);
    altaAutobusosButton.setText("Alta Autobusos");
    gbc = new GridBagConstraints();
    gbc.gridx = 1;
    gbc.gridy = 2;
    gbc.fill = GridBagConstraints.HORIZONTAL;
    panel1.add(altaAutobusosButton, gbc);
    altaConductorsButton = new JButton();
    altaConductorsButton.setText("Alta Conductors");
    gbc = new GridBagConstraints();
    gbc.gridx = 1;
    gbc.gridy = 0;
    gbc.fill = GridBagConstraints.HORIZONTAL;
    panel1.add(altaConductorsButton, gbc);
    final JPanel spacer1 = new JPanel();
    gbc = new GridBagConstraints();
    gbc.gridx = 2;
    gbc.gridy = 3;
    gbc.fill = GridBagConstraints.VERTICAL;
    panel1.add(spacer1, gbc);
    sortirButton = new JButton();
    sortirButton.setText("Sortir");
    gbc = new GridBagConstraints();
    gbc.gridx = 1;
    gbc.gridy = 4;
    gbc.fill = GridBagConstraints.HORIZONTAL;
    panel1.add(sortirButton, gbc);
    final JPanel spacer2 = new JPanel();
    gbc = new GridBagConstraints();
    gbc.gridx = 0;
    gbc.gridy = 4;
    gbc.fill = GridBagConstraints.HORIZONTAL;
    panel1.add(spacer2, gbc);
  }
}
