package vista;

import controlador.Controlador;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.InputMethodEvent;
import java.awt.event.InputMethodListener;

import static javax.swing.JOptionPane.showMessageDialog;

/**
 * Created by joan on 24/05/2016.
 */
public class MenuPrincipalTest extends JFrame implements ActionListener {
  private JPanel menuPrincipal;

  private JButton bAltaConductor;
  private JButton bAltaDeLinies;
  private JButton bAltaDeParades;
  private JButton bAltaDeParadaEnLinea;
  private JButton bAltaConductorVetera;
  private JButton bAltaConductorAprenent;
  private JButton bSortir;
  private JButton altaAutobusosButton;

  private JTextField textField1;
  private JTextField textField2;
  private JTextField textField3;
  private JTextField textField4;

  private Controlador controlador = new Controlador();

  public MenuPrincipalTest() {


    setContentPane(menuPrincipal);

    pack();
    setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);


    setVisible(true);

    bSortir.addActionListener(this);
    bAltaDeLinies.addActionListener(this);
/***
 *
 *   bSortir.addActionListener(new ActionListener() {
 *     @Override
 *     public void actionPerformed(ActionEvent actionEvent) {
 *       System.exit(0);
 *     }
 *   });
 */

    textField1.addInputMethodListener(new InputMethodListener() {
      @Override
      public void inputMethodTextChanged(InputMethodEvent inputMethodEvent) {
        showMessageDialog(MenuPrincipalTest.this, "inputMethodTextChanged" + textField1.toString());
      }

      @Override
      public void caretPositionChanged(InputMethodEvent inputMethodEvent) {
        showMessageDialog(MenuPrincipalTest.this, "caretPositionChanged" + textField1.toString());
      }
    });
    bAltaDeLinies.addActionListener(new ActionListener() {
      @Override
      public void actionPerformed(ActionEvent actionEvent) {
        try {
          controlador.addLinia(Integer.parseInt("0" + textField1.getText().trim()));
          showMessageDialog(MenuPrincipalTest.this, "Guardado correctamente" + textField1.getText());
        } catch (Exception error) {
          System.err.println("Paràmetres incorrectes");
        }

      }
    });
    bSortir.addActionListener(new ActionListener() {
      @Override
      public void actionPerformed(ActionEvent actionEvent) {
        //System.exit(0);
        System.out.println("sortim!!!");
        setVisible(false); //you can't see me!
        dispose(); //Destroy the JFrame object

      }
    });

    altaAutobusosButton.addActionListener(new ActionListener() {
      @Override
      public void actionPerformed(ActionEvent e) {
        try {

          controlador.addautobus(textField2.getText(), Integer.parseInt("0" + textField3.getText().trim()), Integer.parseInt("0" + textField4.getText()));
          showMessageDialog(MenuPrincipalTest.this, "Guardado correctamente" + textField2.getText());
        } catch (Exception error) {
          System.err.println("Paràmetres incorrectes");
        }


      }
    });
    textField2.addInputMethodListener(new InputMethodListener() {
      @Override
      public void inputMethodTextChanged(InputMethodEvent event) {

      }

      @Override
      public void caretPositionChanged(InputMethodEvent event) {

      }
    });
    bAltaConductor.addActionListener(new ActionListener() {
      @Override
      public void actionPerformed(ActionEvent e) {
        new DemanaLinia("Demanar Linia", controlador);
      }
    });
    bAltaDeParades.addActionListener(new ActionListener() {
      @Override
      public void actionPerformed(ActionEvent e) {
        //
        new DemanaAutobusos("Demanar Autobusos", controlador);
      }
    });
    bAltaDeParadaEnLinea.addActionListener(new ActionListener() {
      @Override
      public void actionPerformed(ActionEvent e) {
        new DemanaAutobusCombo("Demanar Autobusos", controlador);
      }
    });
  }

  public static void main(String[] args) {

    MenuPrincipalTest marco = new MenuPrincipalTest();
  }

  @Override
  public void actionPerformed(ActionEvent actionEvent) {
//    System.out.println("Adeu"+actionEvent);
  }

  {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
    $$$setupUI$$$();
  }

  /**
   * Method generated by IntelliJ IDEA GUI Designer
   * >>> IMPORTANT!! <<<
   * DO NOT edit this method OR call it in your code!
   *
   * @noinspection ALL
   */
  private void $$$setupUI$$$() {
    menuPrincipal = new JPanel();
    menuPrincipal.setLayout(new GridBagLayout());
    bAltaConductor = new JButton();
    bAltaConductor.setText("Alta Conductors");
    GridBagConstraints gbc;
    gbc = new GridBagConstraints();
    gbc.gridx = 0;
    gbc.gridy = 0;
    gbc.fill = GridBagConstraints.HORIZONTAL;
    menuPrincipal.add(bAltaConductor, gbc);
    bAltaDeLinies = new JButton();
    bAltaDeLinies.setText("Alta de  Linies");
    gbc = new GridBagConstraints();
    gbc.gridx = 0;
    gbc.gridy = 1;
    gbc.fill = GridBagConstraints.HORIZONTAL;
    menuPrincipal.add(bAltaDeLinies, gbc);
    bAltaDeParades = new JButton();
    bAltaDeParades.setText("Alta de Parades");
    gbc = new GridBagConstraints();
    gbc.gridx = 0;
    gbc.gridy = 3;
    gbc.fill = GridBagConstraints.HORIZONTAL;
    menuPrincipal.add(bAltaDeParades, gbc);
    bAltaDeParadaEnLinea = new JButton();
    bAltaDeParadaEnLinea.setText("Alta de ParadaEnLinea");
    gbc = new GridBagConstraints();
    gbc.gridx = 0;
    gbc.gridy = 4;
    gbc.fill = GridBagConstraints.HORIZONTAL;
    menuPrincipal.add(bAltaDeParadaEnLinea, gbc);
    bAltaConductorVetera = new JButton();
    bAltaConductorVetera.setText("Alta ConductorVetera");
    gbc = new GridBagConstraints();
    gbc.gridx = 0;
    gbc.gridy = 5;
    gbc.fill = GridBagConstraints.HORIZONTAL;
    menuPrincipal.add(bAltaConductorVetera, gbc);
    bAltaConductorAprenent = new JButton();
    bAltaConductorAprenent.setText("Alta ConductorAprenent");
    gbc = new GridBagConstraints();
    gbc.gridx = 0;
    gbc.gridy = 6;
    gbc.fill = GridBagConstraints.HORIZONTAL;
    menuPrincipal.add(bAltaConductorAprenent, gbc);
    final JPanel spacer1 = new JPanel();
    gbc = new GridBagConstraints();
    gbc.gridx = 0;
    gbc.gridy = 7;
    gbc.fill = GridBagConstraints.VERTICAL;
    menuPrincipal.add(spacer1, gbc);
    bSortir = new JButton();
    bSortir.setText("Sortir");
    gbc = new GridBagConstraints();
    gbc.gridx = 0;
    gbc.gridy = 8;
    gbc.fill = GridBagConstraints.HORIZONTAL;
    menuPrincipal.add(bSortir, gbc);
    final JPanel spacer2 = new JPanel();
    gbc = new GridBagConstraints();
    gbc.gridx = 1;
    gbc.gridy = 7;
    gbc.fill = GridBagConstraints.HORIZONTAL;
    menuPrincipal.add(spacer2, gbc);
    textField1 = new JTextField();
    textField1.setColumns(10);
    gbc = new GridBagConstraints();
    gbc.gridx = 2;
    gbc.gridy = 1;
    gbc.anchor = GridBagConstraints.WEST;
    gbc.fill = GridBagConstraints.HORIZONTAL;
    menuPrincipal.add(textField1, gbc);
    altaAutobusosButton = new JButton();
    altaAutobusosButton.setText("Alta Autobusos");
    gbc = new GridBagConstraints();
    gbc.gridx = 0;
    gbc.gridy = 2;
    gbc.fill = GridBagConstraints.HORIZONTAL;
    menuPrincipal.add(altaAutobusosButton, gbc);
    textField2 = new JTextField();
    textField2.setColumns(10);
    textField2.setText("");
    gbc = new GridBagConstraints();
    gbc.gridx = 2;
    gbc.gridy = 2;
    gbc.anchor = GridBagConstraints.WEST;
    gbc.fill = GridBagConstraints.HORIZONTAL;
    menuPrincipal.add(textField2, gbc);
    textField3 = new JTextField();
    textField3.setColumns(10);
    textField3.setText("");
    gbc = new GridBagConstraints();
    gbc.gridx = 3;
    gbc.gridy = 2;
    gbc.anchor = GridBagConstraints.WEST;
    gbc.fill = GridBagConstraints.HORIZONTAL;
    menuPrincipal.add(textField3, gbc);
    textField4 = new JTextField();
    textField4.setColumns(10);
    gbc = new GridBagConstraints();
    gbc.gridx = 4;
    gbc.gridy = 2;
    gbc.anchor = GridBagConstraints.WEST;
    gbc.fill = GridBagConstraints.HORIZONTAL;
    menuPrincipal.add(textField4, gbc);
  }

  /**
   * @noinspection ALL
   */
  public JComponent $$$getRootComponent$$$() {
    return menuPrincipal;
  }
}
