package vista;

import controlador.Controlador;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import static javax.swing.JOptionPane.showMessageDialog;

/**
 * Created by joan on 26/05/2016.
 */
public class MenuPrincipal extends JFrame implements ActionListener {
  private JPanel menuPrincipal;
  private JButton altaConductorsButton;
  private JButton altaLiniesButton;
  private JButton altaAutobusosButton;
  private JButton sortirButton;
  private JButton altaConductorsAprenentsButton;
  private JButton altaParadesButton;
  private JButton altaParadaEnLiniaButton;

  private Controlador controlador = new Controlador();

  public MenuPrincipal() {
    super("Aplicación de autobuses");
//    controlador.llegirLiniesTxt();
//    controlador.llegirLiniesJson();
    controlador.llegirLiniesMySQL();

    setContentPane(menuPrincipal);
    setSize(300, 400);
    //pack();
    setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    altaConductorsAprenentsButton.addActionListener(this);
    altaConductorsButton.addActionListener(this);
    altaLiniesButton.addActionListener(this);
    altaAutobusosButton.addActionListener(this);
    altaParadesButton.addActionListener(this);
    altaParadaEnLiniaButton.addActionListener(this);
    sortirButton.addActionListener(this);

    setVisible(true);
  }

  public static void main(String[] args) {
    MenuPrincipal mP = new MenuPrincipal();

  }

  public void actionPerformed(ActionEvent e) {

    String botoApretat;
    try {
      botoApretat = e.getActionCommand().trim();
    } catch (Exception error) {
      botoApretat = "sortirButton";
      showMessageDialog(this, "Error al introducir datos");
    }

    if (botoApretat.equals("sortirButton")) {
//      controlador.desarLiniesTxt();
      //controlador.desarLiniesJson();
      controlador.desarLiniesMySql();

      System.out.println("Sortim!!!");
      setVisible(false); //you can't see me!
      dispose(); //Destroy the JFrame object

    } else if (botoApretat.equals("altaConductorsButton")) {
      System.out.println("Adeu" + e);
      new DemanaCVetera("Alta Conductor Veterà", controlador);

    } else if (botoApretat.equals("altaConductorsAprenentsButton")) {
      System.out.println("Adeu" + e);
      new DemanaCAprenent("Alta Conductor Aprenent", controlador);

    } else if (botoApretat.equals("altaLiniesButton")) {
      System.out.println("Adeu" + e);
      new DemanaLinia("Demanar Linia", controlador);

    } else if (botoApretat.equals("altaAutobusosButton")) {
      System.out.println("Adeu" + e);
      //new DemanaAutobusos("Demanar Autobusos", controlador);
      new DemanaAutobus("Demanar Autobusos", controlador);

    } else if (botoApretat.equals("altaParadesButton")) {
      System.out.println("Adeu" + e);
      new DemanaParada("Alta de  Parades", controlador);

    } else if (botoApretat.equals("altaParadaEnLiniaButton")) {
      System.out.println("Adeu" + e);
      new DemanaParadaEnLinia("Alta Parades En Linia", controlador);

    }
  }


  {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
    $$$setupUI$$$();
  }

  /**
   * Method generated by IntelliJ IDEA GUI Designer
   * >>> IMPORTANT!! <<<
   * DO NOT edit this method OR call it in your code!
   *
   * @noinspection ALL
   */
  private void $$$setupUI$$$() {
    menuPrincipal = new JPanel();
    menuPrincipal.setLayout(new GridBagLayout());
    altaLiniesButton = new JButton();
    altaLiniesButton.setActionCommand("altaLiniesButton");
    altaLiniesButton.setText("Alta Linies");
    GridBagConstraints gbc;
    gbc = new GridBagConstraints();
    gbc.gridx = 0;
    gbc.gridy = 0;
    gbc.fill = GridBagConstraints.HORIZONTAL;
    menuPrincipal.add(altaLiniesButton, gbc);
    altaAutobusosButton = new JButton();
    altaAutobusosButton.setActionCommand("altaAutobusosButton");
    altaAutobusosButton.setText("Alta Autobusos");
    gbc = new GridBagConstraints();
    gbc.gridx = 0;
    gbc.gridy = 3;
    gbc.fill = GridBagConstraints.HORIZONTAL;
    menuPrincipal.add(altaAutobusosButton, gbc);
    sortirButton = new JButton();
    sortirButton.setActionCommand("sortirButton");
    sortirButton.setText("Sortir");
    gbc = new GridBagConstraints();
    gbc.gridx = 0;
    gbc.gridy = 7;
    gbc.fill = GridBagConstraints.HORIZONTAL;
    menuPrincipal.add(sortirButton, gbc);
    final JPanel spacer1 = new JPanel();
    gbc = new GridBagConstraints();
    gbc.gridx = 0;
    gbc.gridy = 6;
    gbc.fill = GridBagConstraints.HORIZONTAL;
    menuPrincipal.add(spacer1, gbc);
    final JPanel spacer2 = new JPanel();
    gbc = new GridBagConstraints();
    gbc.gridx = 1;
    gbc.gridy = 6;
    gbc.fill = GridBagConstraints.VERTICAL;
    menuPrincipal.add(spacer2, gbc);
    altaConductorsButton = new JButton();
    altaConductorsButton.setActionCommand("altaConductorsButton");
    altaConductorsButton.setText("Alta Conductors Veterans");
    gbc = new GridBagConstraints();
    gbc.gridx = 0;
    gbc.gridy = 2;
    gbc.fill = GridBagConstraints.HORIZONTAL;
    menuPrincipal.add(altaConductorsButton, gbc);
    altaConductorsAprenentsButton = new JButton();
    altaConductorsAprenentsButton.setActionCommand("altaConductorsAprenentsButton");
    altaConductorsAprenentsButton.setText("Alta Conductors Aprenents");
    gbc = new GridBagConstraints();
    gbc.gridx = 0;
    gbc.gridy = 1;
    gbc.fill = GridBagConstraints.HORIZONTAL;
    menuPrincipal.add(altaConductorsAprenentsButton, gbc);
    altaParadesButton = new JButton();
    altaParadesButton.setActionCommand("altaParadesButton");
    altaParadesButton.setText("Alta Parades");
    gbc = new GridBagConstraints();
    gbc.gridx = 0;
    gbc.gridy = 4;
    gbc.fill = GridBagConstraints.HORIZONTAL;
    menuPrincipal.add(altaParadesButton, gbc);
    altaParadaEnLiniaButton = new JButton();
    altaParadaEnLiniaButton.setActionCommand("altaParadaEnLiniaButton");
    altaParadaEnLiniaButton.setText("Alta Parada En Linia");
    gbc = new GridBagConstraints();
    gbc.gridx = 0;
    gbc.gridy = 5;
    gbc.fill = GridBagConstraints.HORIZONTAL;
    menuPrincipal.add(altaParadaEnLiniaButton, gbc);
  }

  /**
   * @noinspection ALL
   */
  public JComponent $$$getRootComponent$$$() {
    return menuPrincipal;
  }
}
